// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMGBIT.Infra.Data.Context;

#nullable disable

namespace SMGBIT.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMGBIT.Core.Entity.TabelaFrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTabela")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Fretes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "CDD Ribeirão Preto",
                            NomeTabela = "table_1",
                            TipoVeiculo = "VUC",
                            Valor = 900.0
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "CDD Ribeirão Preto",
                            NomeTabela = "table_2",
                            TipoVeiculo = "CARRETA",
                            Valor = 812.0
                        },
                        new
                        {
                            Id = 3,
                            Cliente = "CDD Ribeirão Preto",
                            NomeTabela = "table_3",
                            TipoVeiculo = "VAN",
                            Valor = 687.0
                        },
                        new
                        {
                            Id = 4,
                            Cliente = "CDD Ribeirão Preto",
                            NomeTabela = "table_4",
                            TipoVeiculo = "TRUCK",
                            Valor = 702.0
                        },
                        new
                        {
                            Id = 5,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 2",
                            NomeTabela = "table_5",
                            TipoVeiculo = "TRUCK",
                            Valor = 702.0
                        },
                        new
                        {
                            Id = 6,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 10",
                            NomeTabela = "table_6",
                            TipoVeiculo = "TRUCK",
                            Valor = 698.0
                        },
                        new
                        {
                            Id = 7,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 7",
                            NomeTabela = "table_7",
                            TipoVeiculo = "TRUCK",
                            Valor = 900.0
                        },
                        new
                        {
                            Id = 8,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 3",
                            NomeTabela = "table_8",
                            TipoVeiculo = "TRUCK",
                            Valor = 777.0
                        },
                        new
                        {
                            Id = 9,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 3",
                            NomeTabela = "table_9",
                            TipoVeiculo = "VUC",
                            Valor = 532.0
                        },
                        new
                        {
                            Id = 10,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 2",
                            NomeTabela = "table_10",
                            TipoVeiculo = "VUC",
                            Valor = 502.0
                        },
                        new
                        {
                            Id = 11,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 10",
                            NomeTabela = "table_11",
                            TipoVeiculo = "VUC",
                            Valor = 478.0
                        },
                        new
                        {
                            Id = 12,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 7",
                            NomeTabela = "table_12",
                            TipoVeiculo = "VUC",
                            Valor = 690.0
                        },
                        new
                        {
                            Id = 13,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 7",
                            NomeTabela = "table_13",
                            TipoVeiculo = "VAN",
                            Valor = 300.0
                        },
                        new
                        {
                            Id = 14,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 2",
                            NomeTabela = "table_14",
                            TipoVeiculo = "VAN",
                            Valor = 412.0
                        },
                        new
                        {
                            Id = 15,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 3",
                            NomeTabela = "table_15",
                            TipoVeiculo = "VAN",
                            Valor = 400.0
                        },
                        new
                        {
                            Id = 16,
                            Cliente = "CDD São Paulo",
                            Destino = "Regiao 10",
                            NomeTabela = "table_16",
                            TipoVeiculo = "VAN",
                            Valor = 541.0
                        });
                });

            modelBuilder.Entity("SMGBIT.Core.Entity.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaixasCarregadas")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataViagem")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Entregas")
                        .HasColumnType("int");

                    b.Property<int>("KmRodado")
                        .HasColumnType("int");

                    b.Property<string>("Motorista")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumeroViagem")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TabelaViagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoViagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorViagem")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
